<?php

/**
 * AnuncioOpcionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioOpcionalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioOpcionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioOpcional');
    }
}