<?php

/**
 * AnuncioDataBloqueadaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioDataBloqueadaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioDataBloqueadaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioDataBloqueada');
    }
}