<?php

/**
 * AnuncioFavoritoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioFavoritoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioFavoritoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioFavorito');
    }
}