<?php

/**
 * AnuncioReferenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioReferenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioReferenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioReferencia');
    }
}