<?php

/**
 * AnuncioPlanoPagamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioPlanoPagamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioPlanoPagamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioPlanoPagamento');
    }
}