<?php

/**
 * AnuncioDataPersonalizadaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioDataPersonalizadaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioDataPersonalizadaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioDataPersonalizada');
    }
}