<?php

/**
 * ArquivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArquivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArquivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Arquivo');
    }
}