<?php

/**
 * CancelamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CancelamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CancelamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cancelamento');
    }
}