<?php

/**
 * DepoimentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepoimentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepoimentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Depoimento');
    }
}