<?php

/**
 * EquipeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Equipe');
    }
}