<?php

/**
 * ExclusaoContaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExclusaoContaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExclusaoContaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExclusaoConta');
    }
}