<?php

/**
 * GaleriaVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaleriaVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaleriaVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GaleriaVideo');
    }
}