<?php

/**
 * IconeDestaqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IconeDestaqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IconeDestaqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IconeDestaque');
    }
}