<?php

/**
 * ModuloPermissaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModuloPermissaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModuloPermissaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModuloPermissao');
    }
}