<?php

/**
 * NoticiaCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoticiaCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NoticiaCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NoticiaCategoria');
    }
}