<?php

/**
 * OpcionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OpcionalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OpcionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Opcional');
    }
}