<?php

/**
 * PaginaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaginaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaginaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pagina');
    }
}