<?php

/**
 * PerguntaFrequenteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerguntaFrequenteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerguntaFrequenteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerguntaFrequente');
    }
}