<?php

/**
 * RamoAtividadeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RamoAtividadeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RamoAtividadeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RamoAtividade');
    }
}