<?php

/**
 * ReservaAvaliacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservaAvaliacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservaAvaliacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReservaAvaliacao');
    }
}