<?php

/**
 * RespostaAutomaticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RespostaAutomaticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RespostaAutomaticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RespostaAutomatica');
    }
}