<?php

/**
 * SobreNosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SobreNosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SobreNosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SobreNos');
    }
}