<?php

/**
 * SolicitacaoSaqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolicitacaoSaqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolicitacaoSaqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SolicitacaoSaque');
    }
}