<?php

/**
 * StatusSaqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatusSaqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatusSaqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatusSaque');
    }
}