<?php

/**
 * TipoPessoaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoPessoaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoPessoaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoPessoa');
    }
}