<?php

/**
 * TipoTransacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoTransacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoTransacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoTransacao');
    }
}