<?php

/**
 * TipoCobrancaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoCobrancaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoCobrancaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoCobranca');
    }
}