<?php

/**
 * UnidadeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Unidade');
    }
}