<?php



/**

 * UsuarioPermissao

 *

 * This class has been auto-generated by the Doctrine ORM Framework

 *

 * @package    ##PACKAGE##

 * @subpackage ##SUBPACKAGE##

 * @author     ##NAME## <##EMAIL##>

 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $

 */

class UsuarioPermissao extends BaseUsuarioPermissao

{



    public function getMenu($parent){


        if($_SESSION['sess_usuario_id']==1){
            $where = "1=1";
        }else{
            $where = "p.id in (select `usuario_permissao_id` from `modulo_permissao`)";
        }


        // Seleciona a permissão

        $retPermissao = Doctrine_Query::create()

            ->from('UsuarioPermissao p')

            ->innerJoin('p.UsuarioGrupoPermissao g')

            ->addWhere('g.usuario_grupo_id = '.$_SESSION['sess_usuario_grupo_id'])

            ->addWhere('p.tipo = 0')

            ->addWhere('p.parent = '.$parent)

            ->addWhere('p.status = 1')

            ->addWhere($where)

            ->addOrderBy('p.ordem ASC');



        // Verifica se houve retorno

        if ($retPermissao->count() > 0){

            // Resultado

            $resPermissao = $retPermissao->fetchArray();





            foreach ($resPermissao as $res){

                // Montagem de URL

                $url = empty($res['model'])?'#':URL_ADMIN.$res['model'].'/';

                $url .= empty($res['action'])?'':$res['action'].'/';

                $arrow = $this->checkChildren($res['id'], 0)?'<span class="menu-arrow"></span>':'';

                $desenvolvimento = isset($res['desenvolvimento'])&&$res['desenvolvimento']==1?"concluido":"";

                echo '<li><a class="'.$desenvolvimento.'" href="'.$url.'"><i class="'.$res['icone'].'"></i><span>'.$res['titulo'].'</span>'.$arrow.'</a>';



                if ($this->checkChildren($res['id'], 0)){

                    echo '<ul class="nav-second-level" aria-expanded="false">';

                    $this->getMenu($res['id']);

                    echo '</ul>';

                }



                echo '</li>';

            }



        }



    }



    public function getPermission($parent, $usuario_grupo_id){



        // Seleciona a permissão

        $retPermissao = Doctrine_Query::create()

            ->from('UsuarioPermissao p')

            ->addWhere('p.parent = '.$parent)

            ->addWhere('p.status = 1')

            ->addOrderBy('p.ordem ASC');



        // Verifica se houve retorno

        if ($retPermissao->count() > 0){

            // Resultado

            $resPermissao = $retPermissao->fetchArray();



            foreach ($resPermissao as $res){

                // Checa se o grupo possui a permissão

                $checked = Doctrine_Core::getTable('UsuarioGrupoPermissao')->findByUsuarioGrupoIdAndUsuarioPermissaoId($usuario_grupo_id, $res['id']);

                $checked = $checked->count()==1?'checked="checked"':'';



                // Imprime a permissão

                echo '<li><label><input type="checkbox" '.$checked.' name="usuario_permissao_id[]" class="icheck" parent="'.$res['parent'].'" value="'.$res['id'].'" /> '.$res['titulo'],'</label></li>';



                if ($this->checkChildren($res['id'], null)){

                    echo '<ul  style="padding-left: 30px !important; list-style: none !important;">';

                    $this->getPermission($res['id'], $usuario_grupo_id);

                    echo '</ul>';

                }



            }



        }



    }



    private function checkChildren($usuario_permissao_id, $tipo = 0){

        if (is_null($tipo)){

            $ret = Doctrine_Core::getTable('UsuarioPermissao')->findByParent($usuario_permissao_id);

        } else {

            $ret = Doctrine_Core::getTable('UsuarioPermissao')->findByParentAndTipo($usuario_permissao_id,0);

        }



        if ($ret->count() > 0){

            return true;

        } else {

            return false;

        }



    }



    public function getPermissao($model, $tipo, $action = ''){

        // Tratamento no action

        $action = explode('_', $action);

        $action = $action[0];



        // Condição de busca por tipo

        if (is_array($tipo)){

            $where = '';

            foreach ($tipo as $value){

                $where .= $where==''?'p.tipo = '.$value:' OR p.tipo = '.$value;

            }

            $tipo = $where;

        } else {

            $tipo = 'p.tipo = '.$tipo;

        }



        // Busca por permissão de acesso

        $retPermissao = Doctrine_Query::create()

            ->from('UsuarioPermissao p')

            ->innerJoin('p.UsuarioGrupoPermissao g')

            ->addWhere('g.usuario_grupo_id = '.$_SESSION['sess_usuario_grupo_id'])

            ->addWhere($tipo)

            ->addWhere('p.model = "'.$_GET['model'].'"')

            ->addWhere('p.status = 1')
            ->addOrderBy('p.ordem ASC');



        // Verifica se o action foi enviado e adidiona a query

        if ($action != ''){

            $retPermissao->addWhere('p.action LIKE "%'.$action.'%"');

        }



        if ($retPermissao->count() > 0){

            return $retPermissao->fetchArray();

        } else {

            return false;

        }



    }



    public function printActions($model,$tipo,$id= 0,$action = ''){

        // Tratamento no action

        $action = explode('_', $action);

        $action = $action[0];



        $id = $id!='0'?$id.'/':'';



        // Busca por permissão de acesso

        $retPermissao = Doctrine_Query::create()

            ->from('UsuarioPermissao p')

            ->innerJoin('p.UsuarioGrupoPermissao g')

            ->addWhere('g.usuario_grupo_id = '.$_SESSION['sess_usuario_grupo_id'])

            ->addWhere('p.tipo = '.$tipo)

            ->addWhere('p.status = 1')
            ->addWhere('p.model = "'.$model.'"');



        // Verifica se o action foi enviado e adidiona a query

        if ($action != ''){

            $retPermissao->addWhere('p.action LIKE "%'.$action.'%"');

        }



        if ($retPermissao->count() > 0){

            $retPermissao = $retPermissao->fetchArray();

            echo '<div class="actionbar" style="margin: 10px;">';

            foreach ($retPermissao as $resPermissao){

                echo '<a href="'.URL_ADMIN.$resPermissao['model'].'/'.$resPermissao['action'].'/'.$id.'" data-toggle="tooltip" data-original-title="'.$resPermissao['titulo'].'" style="border: 1px solid #CCC; color: #BC0404;height: 30px; padding: 3px 10px 3px 3px; border-radius: 5px;"><i class="'.$resPermissao['icone'].'" style="background: transparent; border: 0px"></i> Cadastrar</a>';

            }

            echo '</div>';

        } else {

            return false;

        }

    }



}