<?php

/**
 * VariacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VariacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VariacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Variacao');
    }
}